---
kind: secret
name: google_credentials_dev
get:
  path: nytimes/teams/nyt-cms-devs/secret/gcp/GOOGLE_CREDENTIALS_DEV
  name: base64
---
kind: secret
name: test_secret
get:
  path: nytimes/teams/nyt-cms-devs/secret/gcp/GOOGLE_CREDENTIALS_DEV
  name: x-auth-secrets-copy
---
kind: pipeline
name: Build and deploy
steps:
  - name: Build
    pull: if-not-exists
    image: node:16
    commands:
      - echo ${TEST_SECRET}
      - yarn install
      - yarn build
    environment:
      TEST_SECRET:
        from_secret: test_secret

  - name: Deploy to GAE
    pull: if-not-exists
    image: nytimes/drone-gae
    settings:
      action: deploy
      max_versions: 1
      project: nyt-cms-dev
      version: ${DRONE_COMMIT}
      addl_flags:
        - --promote
    environment:
      GAE_CREDENTIALS:
        from_secret: google_credentials_dev

trigger:
  event: push
  branch: main
