env: standard
runtime: python310
service: oak-pm-react-week

handlers:
  - url: /$
    secure: always
    static_files: out/index.html
    upload: out/index.html

  - url: /(.*)/$
    static_files: out/\1/index.html
    upload: out/.*/index.html

  - url: /(.+)
    static_files: out/\1
    upload: out/(.*)
